"""Grok-powered HTML email generation."""

import json
import logging
import os
import random
from datetime import datetime
from pathlib import Path
from openai import OpenAI

from . import stats

logger = logging.getLogger(__name__)

# Cache directory for generated HTML (inside project root)
CACHE_DIR = Path(__file__).parent.parent.parent / "cache"

# Models to randomly choose from for HTML generation (50/50 split)
HTML_MODELS = ["grok-code-fast-1", "grok-4-fast-reasoning"]


def _truncate_content(content: str, max_length: int = 1500) -> str:
    """Truncate content to max_length, adding ellipsis if truncated."""
    if len(content) <= max_length:
        return content
    return content[:max_length].rsplit(" ", 1)[0] + "..."


def _save_to_cache(html: str, posts: list[dict], model: str) -> Path:
    """
    Save generated HTML and input posts to cache directory.

    Returns the path to the saved HTML file.
    """
    CACHE_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # Include model in filename for A/B comparison
    base_name = f"digest_{timestamp}_{model}"

    html_path = CACHE_DIR / f"{base_name}.html"
    json_path = CACHE_DIR / f"{base_name}.json"

    # Save HTML
    html_path.write_text(html, encoding="utf-8")

    # Save input posts for debugging prompt iterations
    json_path.write_text(json.dumps(posts, indent=2), encoding="utf-8")

    logger.info(f"Cached digest to {html_path}")
    return html_path


def get_client() -> OpenAI:
    """Get an OpenAI client configured for xAI."""
    api_key = os.getenv("XAI_API_KEY")
    if not api_key:
        raise ValueError("XAI_API_KEY environment variable not set")

    return OpenAI(
        api_key=api_key,
        base_url="https://api.x.ai/v1",
    )


def generate_html(posts: list[dict]) -> str:
    """
    Generate a styled HTML email for the digest using Grok.

    Grok has full creative freedom to style the email based on the content.

    Args:
        posts: List of post dicts with keys:
            - title, url, subreddit, content, grok_reason

    Returns:
        Complete HTML document as a string
    """
    client = get_client()

    # Format posts for the prompt (include more content for richer emails)
    posts_data = [
        {
            "title": p["title"],
            "url": p["url"],
            "subreddit": f"r/{p['subreddit']}",
            "content": _truncate_content(p.get("content", ""), 1500),
            "why_included": p.get("grok_reason", ""),
            "posted": p.get("published_at", ""),
        }
        for p in posts
    ]
    posts_summary = json.dumps(posts_data, indent=2)

    prompt = f"""Generate a complete HTML email for a personal content digest. Style the page to match the vibe and content of the posts below. Full creative freedom - be artistic, experimental, fun. Make it visually interesting and unique.

The email should:
- Be a single self-contained HTML document
- Include ALL CSS inline or in a <style> tag (no external stylesheets)
- Make post titles PROMINENT CLICKABLE LINKS to the Reddit posts (style them to stand out with color, underline, hover effects)
- Display the post content/snippet for each post (make it readable, use appropriate formatting)
- Show which subreddit each post is from
- Show when each post was posted (relative time like "2 hours ago" or the date)
- Include the curator's reason for including each post (this explains why it was selected)
- Have a header/title for the digest
- Include the date: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
- Be readable on both desktop and mobile

POSTS TO INCLUDE:
{posts_summary}

Output ONLY the HTML document, no explanation or markdown code fences."""

    # Randomly pick a model for variety in email styles
    model = random.choice(HTML_MODELS)
    logger.info(f"Using {model} for HTML generation")

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4000,
        temperature=0.8,  # Higher temp for creativity
    )

    # Track API usage
    current_stats = stats.get_current_stats()
    if current_stats and response.usage:
        current_stats.add_api_call(
            model=model,
            purpose="html",
            input_tokens=response.usage.prompt_tokens,
            output_tokens=response.usage.completion_tokens,
        )

    html = response.choices[0].message.content.strip()

    # Add a hidden comment showing which model generated this
    html = html.replace("</html>", f"\n<!-- Generated by {model} -->\n</html>")

    # Clean up if Grok wrapped it in code fences
    if html.startswith("```html"):
        html = html[7:]
    if html.startswith("```"):
        html = html[3:]
    if html.endswith("```"):
        html = html[:-3]

    html = html.strip()

    # Cache the generated HTML and input data for debugging
    _save_to_cache(html, posts_data, model)

    return html


def generate_plain_text(posts: list[dict]) -> str:
    """
    Generate a plain text fallback for the email.

    Args:
        posts: List of post dicts

    Returns:
        Plain text version of the digest
    """
    lines = [
        f"Reddit Digest - {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        "=" * 50,
        "",
    ]

    for post in posts:
        posted = post.get('published_at', '')
        posted_str = f" | Posted: {posted}" if posted else ""
        lines.extend([
            f"[r/{post['subreddit']}{posted_str}] {post['title']}",
            f"Link: {post['url']}",
            f"Why: {post.get('grok_reason', 'N/A')}",
            "",
            "-" * 30,
            "",
        ])

    lines.append("Generated by Reddit Digest")
    return "\n".join(lines)
