"""Grok-powered HTML email generation."""

import json
import logging
import os
import random
from datetime import datetime
from openai import OpenAI

logger = logging.getLogger(__name__)

# Models to randomly choose from for HTML generation (50/50 split)
HTML_MODELS = ["grok-code-fast-1", "grok-4-fast-reasoning"]


def get_client() -> OpenAI:
    """Get an OpenAI client configured for xAI."""
    api_key = os.getenv("XAI_API_KEY")
    if not api_key:
        raise ValueError("XAI_API_KEY environment variable not set")

    return OpenAI(
        api_key=api_key,
        base_url="https://api.x.ai/v1",
    )


def generate_html(posts: list[dict]) -> str:
    """
    Generate a styled HTML email for the digest using Grok.

    Grok has full creative freedom to style the email based on the content.

    Args:
        posts: List of post dicts with keys:
            - title, url, subreddit, content, grok_reason

    Returns:
        Complete HTML document as a string
    """
    client = get_client()

    # Format posts for the prompt
    posts_summary = json.dumps(
        [
            {
                "title": p["title"],
                "url": p["url"],
                "subreddit": f"r/{p['subreddit']}",
                "snippet": p.get("content", "")[:300],
                "why_included": p.get("grok_reason", ""),
            }
            for p in posts
        ],
        indent=2,
    )

    prompt = f"""Generate a complete HTML email for a personal content digest. Style the page to match the vibe and content of the posts below. Full creative freedom - be artistic, experimental, fun. Make it visually interesting and unique.

The email should:
- Be a single self-contained HTML document
- Include ALL CSS inline or in a <style> tag (no external stylesheets)
- Make post titles clickable links to the Reddit posts
- Show which subreddit each post is from
- Include the curator's reason for including each post
- Have a header/title for the digest
- Include the date: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
- Be readable on both desktop and mobile

POSTS TO INCLUDE:
{posts_summary}

Output ONLY the HTML document, no explanation or markdown code fences."""

    # Randomly pick a model for variety in email styles
    model = random.choice(HTML_MODELS)
    logger.info(f"Using {model} for HTML generation")

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4000,
        temperature=0.8,  # Higher temp for creativity
    )

    html = response.choices[0].message.content.strip()

    # Add a hidden comment showing which model generated this
    html = html.replace("</html>", f"\n<!-- Generated by {model} -->\n</html>")

    # Clean up if Grok wrapped it in code fences
    if html.startswith("```html"):
        html = html[7:]
    if html.startswith("```"):
        html = html[3:]
    if html.endswith("```"):
        html = html[:-3]

    return html.strip()


def generate_plain_text(posts: list[dict]) -> str:
    """
    Generate a plain text fallback for the email.

    Args:
        posts: List of post dicts

    Returns:
        Plain text version of the digest
    """
    lines = [
        f"Reddit Digest - {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        "=" * 50,
        "",
    ]

    for post in posts:
        lines.extend([
            f"[r/{post['subreddit']}] {post['title']}",
            f"Link: {post['url']}",
            f"Why: {post.get('grok_reason', 'N/A')}",
            "",
            "-" * 30,
            "",
        ])

    lines.append("Generated by Reddit Digest")
    return "\n".join(lines)
